### ISSUE TITLE
Make it work without a key in the configs

### ISSUE THREAD

**Issue by gergelypolonkai** [wakatime/wakatime-mode#18]
As I can put my API key in the wakatime config file (`~/.wakatime.cfg`), why do I **have to** put it in my `init.el`, too? This is especially bad for people who publish their emacs settings somewhere.

**Comment by alanhamlett** [comment]
Good point. To do this we need an elisp function to check if the api key is defined and valid format when first starting Emacs, prompt for it if not defined, and save it to `~/.wakatime.cfg`.

**Comment by gergelypolonkai** [comment]
Parsing the config from Emacs seems tricky for me, and I don’t think it’s a good idea at all (I mean, reading the wakatime config every time Emacs starts). How about just trying to run the command without `--key` and check the output if it actually complains about the missing key?

**Comment by gergelypolonkai** [comment]
OK, the key validity checking is more tricky :)

It seems to me that the API accepts the key with any dashes: `0123456789abcdef0123456789abcdef` is as valid as `0-1-2-3-4-5-6-7-8-9-a-b-c-d-e-f-0-1-2-3-4-5-6-7-8-9-a-b-c-d-e-f`.

Here are my two cents:

    (string-match "^[[:xdigit:]]\\{32\\}$"
                  (replace-regexp-in-string "-" "" wakatime-api-key))

**Comment by alanhamlett** [comment]
Checking the [return code](https://github.com/wakatime/wakatime/blob/master/wakatime/constants.py#L14) of wakatime-cli would tell wakatime-mode if the api key was valid or not. 102 means invalid api key. If the return code is 102 then wakatime-mode can lazily prompt for the api key.

**Comment by alanhamlett** [comment]
Fixed with #19 and #21.
