### ISSUE TITLE
error in process sentinel (osx11.11.6 emacs24.5)

### ISSUE THREAD

**Issue by oucb** [wakatime/wakatime-mode#20]
when i use **`(setq wakatime-cli-path “/usr/local/bin/wakatime”)`**，error in process sentinel...(pip install wakatime)
then i set **wakatime-cli-path** to **“/Library/Python/2.7/site-packages/wakatime/cli.py”** ，works well

**Comment by alanhamlett** [comment]
Should be fixed with 7172a92df66a69537c849182c22404715ddd9bfe.
