### ISSUE TITLE
Unbound value for retrying

### ISSUE THREAD

**Issue by gergelypolonkai** [wakatime/wakatime-mode#22]
After you merged my modifications in #21, I used wakatime-mode without an internet connection. I get this error:

    error in process sentinel: progn: Symbol’s value as variable is void: retrying
    error in process sentinel: Symbol’s value as variable is void: retrying

This is logical, as the `retrying` variable is not bound in the lambda of the process sentinel (I don’t know how I will solve this, but I will).

However, what is more problematic, that part of code should only run if the exit code of the `wakatime` CLI process is 102 (see [here](/wakatime/wakatime-mode/blob/77dc9a8236d4324e3781ed11c7c8617d58f31545/wakatime-mode.el#L189)).

Do you think it is possible the CLI process exits with 102 if there is no network connection? (If so, I will open an issue for [wakatime/wakatime](/wakatime/wakatime).

**Comment by alanhamlett** [comment]
Fixed with #23.
