### ISSUE TITLE
wakatime-call: Wrong type argument: number-or-marker-p, [Wakatime CLI Path]

### ISSUE THREAD

**Issue by peterbecich** [wakatime/wakatime-mode#28]
I just updated to Wakatime-mode 20170319.2117
My Wakatime Python CLI is version 8.0.0

```
wakatime-call: Wrong type argument: number-or-marker-p, "/Users/peterbecich/.virtualenv/ENV/bin/wakatime"
```
The latest version of wakatime-mode doesn't seem to like my `wakatime-cli-path` variable.

<img width="522" alt="screen shot 2017-03-20 at 6 02 27 pm" src="https://cloud.githubusercontent.com/assets/6315338/24128691/c3757048-0d9a-11e7-9275-aceaef1a6fdf.png">

Typing in a buffer with the Wakatime minor mode enabled produces the `Wrong type argument` error:

<img width="673" alt="screen shot 2017-03-20 at 6 03 40 pm" src="https://cloud.githubusercontent.com/assets/6315338/24128698/ce381e0e-0d9a-11e7-9663-1d04fa9f98cd.png">

Disabling the Wakatime minor mode solves the problem.

I believe the path to the CLI is correct:

```
Dione:bin peterbecich$ which wakatime
/Users/peterbecich/.virtualenv/ENV/bin/wakatime
```

I think the utility and `cfg` file are file:
```
Dione:bin peterbecich$ which wakatime
/Users/peterbecich/.virtualenv/ENV/bin/wakatime
Dione:bin peterbecich$ wakatime
usage: wakatime [-h] [--entity FILE] [--key KEY] [--write] [--plugin PLUGIN]
                [--time time] [--lineno LINENO] [--cursorpos CURSORPOS]
                [--entity-type ENTITY_TYPE] [--proxy PROXY]
                [--project PROJECT] [--alternate-project ALTERNATE_PROJECT]
                [--language LANGUAGE] [--hostname HOSTNAME] [--disableoffline]
                [--hidefilenames] [--exclude EXCLUDE] [--include INCLUDE]
                [--extra-heartbeats] [--logfile LOGFILE] [--apiurl API_URL]
                [--timeout TIMEOUT] [--config CONFIG] [--verbose] [--version]
wakatime: error: argument --entity is required
```

Wakatime is terrific -- thanks!

**Comment by sungkmi** [comment]
I have the same symptom, too.

**Comment by alanhamlett** [comment]
Does 93f684c88fa73dee97502a8364e8e8b8a0389fd4 fix it?

**Comment by andrew-christianson** [comment]
I believe your issue is [here](https://github.com/wakatime/wakatime-mode/blob/master/wakatime-mode.el#L153).  The `=` function is not (no longer?) a valid equality test for strings e.g. even `(= "abc" "abc") fails `number-or-marker-p`.   I think if you change the `=` in those lines (and other string comparisons) to `string=` you should be in good shape.

**Comment by alanhamlett** [comment]
@andrew-christianson thanks, fixed with 802d6a52cae14f66844e06fd403bf0c3783ad841.

**Comment by peterbecich** [comment]
Latest MELPA package fixes it.  Thanks!

**Comment by andrew-christianson** [comment]
@alanhamlett one more fix required to resolve this for me.  This [line](https://github.com/wakatime/wakatime-mode/blob/master/wakatime-mode.el#L82) makes the rest of the function do the wrong thing, as there isn't an else side to an `unless`, just `(unless COND BODY...)`.  So, it returns `nil`, even when correctly guessing the script path.  Removing the final `nil` appears to resolve the issue on my machine!

**Comment by alanhamlett** [comment]
@andrew-christianson thanks, should be fixed in the latest MELPA update.

**Comment by ryukinix** [comment]
Same problem here
