### ISSUE TITLE
WakaTime Error (127)

### ISSUE THREAD

**Issue by Fibrasek** [wakatime/wakatime-mode#35]
Hello guys!

I keep receiving this error everytime:
```
error in process sentinel: WakaTime Error (127) Make sure this command runs in a Terminal: wakatime --file "/home/fibrasek/dotfiles/.emacs.d/init.el" --plugin "emacs-wakatime/1.0.2" --time 1531854843.23 --key <omitted>
```

And my configuration in `init.el` is the following:
```
(use-package wakatime-mode :ensure t
  :init (global-wakatime-mode)
  :config (setq wakatime-api-key "<omited>"
                wakatime-cli-path "/home/fibrasek/.local/bin/wakatime"
                wakatime-python-bin "/usr/bin/python"))
```

Am I doing something wrong?

**Comment by coffee-cup** [comment]
I have recently started getting this error too.

**Comment by kermorgant** [comment]
had this problem too, I believe it happened after a system upgrade.

I solved that by reinstalling wakatime (``sudo pip install wakatime`` in my case)

**Comment by clvrobj** [comment]
The problem solved after I set up `wakatime-cli-path` key in my init.el.
(setq wakatime-cli-path "the path of [which wakatime]")

**Comment by einSelbst** [comment]
This is the config I'm using, thanks to some random user's emacs init I found via github search:
```
;; Time Tracking
(use-package wakatime-mode
  :diminish 'wakatime-mode
  :init
  (add-hook 'prog-mode-hook 'wakatime-mode)
  :config (progn (setq wakatime-cli-path "/usr/local/bin/wakatime")
                 (setq wakatime-python-bin nil)
                 (global-wakatime-mode)))
```
I do set the api key in the `~/.wakatime.cfg`
```
[settings]
debug = false
api_key = 2a1a183b-fooo-baar-b97b-foobaar
```
