### ISSUE TITLE
error in sentinel process

### ISSUE THREAD

**Issue by chrisoswald** [wakatime/wakatime-mode#41]
Hello,
I'm using wakatime with emacs under windows and get the error 
`error in process sentinel: WakaTime Error (1) Make sure this command runs in a Terminal: `

` c:/Users/Christian Oswald/AppData/Local/Programs/Python/Python36-32/Scripts/wakatime.exe --file "c:/Users/Christian Oswald/Documents/workspace/komi/R/funktionen/f_aufwendungen.R" --plugin "emacs-wakatime/1.0.2" --time 1565018926.30`

The problem comes from the blank space in the path of the command. Is there a possibility to change something that the command is running properly?

Thanks,
Christian

**Comment by einSelbst** [comment]
I'm getting a similar error on OSX 10.13.6, Emacs 26.3.

The command runs fine in the terminal and also in eshell.

**Comment by gandarez** [comment]
@alanhamlett help on this

**Comment by oiwn** [comment]
Same for vim.

**Comment by alanhamlett** [comment]
Sorry, this was me. 😭 I broke the api key parsing, but it's fixed now. The plugin saves your stats and syncs them up the next time the plugin runs (the next time you're typing) so nothing is lost, but still sorry about the frustration it may have caused.
