### ISSUE TITLE
error in process sentinel: WakaTime Error (104) Invalid API Key

### ISSUE THREAD

**Issue by nitinprakash96** [wakatime/wakatime-mode#43]
Editor: `spacemacs`
Platform: `MacOS`

I'm not sure why this is happening. It was working perfectly fine the other day. But this error has been constant throught since this morning.
I made sure the API key is set properly in my emacs (actually I haven't made any changes to my emacs config).
Is there a way to troubleshoot this?

**Comment by oiwn** [comment]
same issue bot emacs (spacemacs) and vim.

There is ticket from 2018 with comment:

> This was a temporary problem on our end and should be fixed now.

**Comment by h-des** [comment]
Neovim error:
```
Error detected while processing function <SNR>30_NeovimAsyncExitHandler:
line    6:
[WakaTime] Error 104: Invalid API Key
```

**Comment by oiwn** [comment]
> Neovim error:
> 
> ```
> Error detected while processing function <SNR>30_NeovimAsyncExitHandler:
> line    6:
> [WakaTime] Error 104: Invalid API Key
> ```

yea exactly same trace.

**Comment by kongds** [comment]
same issue

`➜  ~ /usr/local/bin/wakatime  --key <api-key> --entity .`
`➜  ~ echo $?`
`104`

In python source code,`wakatime/api.py`:  `send_hearbeat` function return 401 with `{"error":"Unauthorized"}` (version 13.0.7)

**Comment by kadircancetin** [comment]
Same issue. I had to disable wakatime mode. I have never set the` wakatime-api-key`. It was writen in `.wakatime.cfg` file. Error is:

`
error in process sentinel: cond: WakaTime Error (104) Invalid API Key. Set your api key with: (custom-set-variables ’(wakatime-api-key "XXXX"))`

**Comment by thomasf** [comment]
and it really slows emacs down a lot, the mode should disable itself or something if it fails to start.

**Comment by emacsified** [comment]
This issue appears to be a global issue (see below) But I am also getting this

- https://github.com/wakatime/jetbrains-wakatime/issues/146
- https://github.com/wakatime/vscode-wakatime/issues/143
- https://github.com/wakatime/wakatime/issues/221

**Comment by alanhamlett** [comment]
Sorry, this was me. 😭 I broke the api key parsing, but it's fixed now. The plugin saves your stats and syncs them up the next time the plugin runs (the next time you're typing) so nothing is lost, but still sorry about the frustration it may have caused.

**Comment by nitinprakash96** [comment]
> Sorry, this was me. 😭 I broke the api key parsing, but it's fixed now. The plugin saves your stats and syncs them up the next time the plugin runs (the next time you're typing) so nothing is lost, but still sorry about the frustration it may have caused.

Thanks a lot for fixing it @alanhamlett 
Cheers!
