### ISSUE TITLE
Wakatime mode doesn't specify a license file

### ISSUE THREAD

**Issue by markgdawson** [wakatime/wakatime-mode#54]
It isn't clear to me if it is permissible for the code to be forked for use in a derivative work.

**Comment by thomasf** [comment]
Check the header of the elisp files. it's GPL.

**Comment by thomasf** [comment]
Also, you can't just add a licence after the fact to a project unless you get the explicit permission by everyone who as contributed so it's not just a matter of adding a file.

**Comment by markgdawson** [comment]
Thanks @thomasf. And thanks for pointing that out, I hadn't realised.

**Comment by alanhamlett** [comment]
Closing since I didn't hear back from the original repo owner.
