### ISSUE TITLE
Wakatime Error (6) in Doom Emacs

### ISSUE THREAD

**Issue by Yescafe** [wakatime/wakatime-mode#61]
Hi, I am using DOOM v21.12.0-alpha and install wakatime-mode and wakatime-cli correctly by installation guide. But it always show these error info:

<img width="1594" alt="image" src="https://user-images.githubusercontent.com/25558466/155652830-3da3c9c6-4761-445f-a196-dcc783a92a52.png">

I think my config is not wrong, and variable settings is correct.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/25558466/155652921-2103bc8e-9317-45b6-9c5f-5b2b935c31cd.png">

Please help me, thanks.

**Comment by Yescafe** [comment]
My Emacs version is 27.2 and OS is macOS Monterey.

**Comment by Yescafe** [comment]
The problem solved itself, but I don't know what is wrong before.

**Comment by alanhamlett** [comment]
Glad it's working.. maybe something changed after restarting your emacs?
