### ISSUE TITLE
Wakatime doesn't prompt for api key

### ISSUE THREAD

**Issue by Borwe** [wakatime/wakatime-mode#63]
Emacs 28.1

**Comment by alanhamlett** [comment]
Can you try with the latest version? This might have been fixed with #64.

**Comment by Borwe** [comment]
LOL, I am the one who did the PR. But cool, can now prompt manually. Though would be cool if it could download the executable like happens in vim version. But it's cool.

**Comment by alanhamlett** [comment]
Yea, let's use the same install script as Vim and run it if `~/.wakatime/wakatime-cli` isn't present.
