### ISSUE TITLE
wakatime mode keep stealing focus when it fails

### ISSUE THREAD

**Issue by contrun** [wakatime/wakatime-mode#66]
If wakatime mode failed to setup, it would continuously retry. The thing baffles me is that every time wakatime fails, it would steal my editor's focus. That is to say, I can't edit my files any more. I think it would be better if wakatime would silently fail and have some sort of back-off strategy.

Wakatime mode steals focus while outputting the following messages.
```
error in process sentinel: cond: WakaTime Error (112) Make sure this command runs in a Terminal: "wakatime-cli" --entity /home/e/.local/share/chezmoi/Makefile --plugin "emacs-wakatime/1.0.2" --time 1664073120.67 --key f3ef8822-7af0-4efe-9677-90e9ad577777
error in process sentinel: WakaTime Error (112) Make sure this command runs in a Terminal: "wakatime-cli" --entity /home/e/.local/share/chezmoi/Makefile --plugin "emacs-wakatime/1.0.2" --time 1664073120.67 --key f3ef8822-7af0-4efe-9677-90e9ad57777
```

**Comment by Borwe** [comment]
I believe this was fixed by [this](https://github.com/wakatime/wakatime-mode/commit/ef923829912c3854d230834f81083814b7c9d992)
