### ISSUE TITLE
Using `venv-workon` or any tool that changes current python venv makes wakatime unusable.

### ISSUE THREAD

**Issue by CestDiego** [wakatime/wakatime-mode#7]
This is because default wakatime-python-bin is `python`. Should support absolute path to the virtualenv wakatime is installed on, or otherwise provide instructions in setting this variable for yourself if you use venv-workon or sth like that.

**Comment by CestDiego** [comment]
This can be fixed by specifying the `wakatime-python-bin` explicitly like so:

**Comment by alanhamlett** [comment]
Duplicate of #16.
