### ISSUE TITLE
emacs not working but terminal worked

### ISSUE THREAD

**Issue by peter159** [wakatime/wakatime-mode#76]
Hi,

I'm using this wakatime-mode, it was good. but when I upgrade a version, it not working in emacs, but working in terminal. some of the snapshot:

the command is essentially:  
/usr/bin/zsh -c '~/.wakatime/wakatime-cli --entity /tracked/file/name/xxx.py --plugin "emacs-wakatime/1.0.2" --time 1711266057.48 --write --key waka_aef****'

the log is:
{"caller":"cmd/run.go:341","file":"/tracked/file/name/xxx.py","func":"cmd.runCmd","is_write":true,"level":"error","message":"failed to run command: sending heartbeat(s) failed: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","now":"2024-03-24T15:54:32+08:00","os/arch":"linux/amd64","plugin":"emacs-wakatime/1.0.2","time":1711266751.88,"version":"v1.90.0"}

same command when I run in WSL2 terminal, it worked and log show working correct

can you help me figure out how is this happening?

**Comment by gandarez** [comment]
Closing in order to have wakatime cli issue opened.
