### ISSUE TITLE
Wakatime doesn't not recognise Luau as a programming language

### ISSUE THREAD

**Issue by prooheckcp** [wakatime/wakatime-mode#79]
I often work on luau projects but wakatime labels these files as "Other"

![image](https://github.com/user-attachments/assets/523abb1a-f89f-4388-b607-6f0e2b36e15f)

Language is recognised by GitHub as seen here:
https://github.com/github-linguist/linguist/releases/tag/v7.30.0

**Comment by alanhamlett** [comment]
Fixed, thanks!
