### ISSUE TITLE
Add a way to exclude certain languages/projects?

### ISSUE THREAD

**Issue by x-ji** [wakatime/wakatime-mode#9]
For example org-mode is generally used for taking notes, not necessarily programming. I leave it open all day and including such data is likely to be misleading.

**Comment by CestDiego** [comment]
I think you can use a `~/.wakatime.cfg` to exclude stuff

**Comment by alanhamlett** [comment]
that's right, @x-ji would the exclude config work for you?
https://github.com/wakatime/wakatime#configuring

**Comment by alanhamlett** [comment]
More info here:

https://wakatime.com/faq#exclude-paths
